name: Publish Interfaces Package to npmjs

on:
  push:
    tags: ['v[0-9]+.[0-9]+.[0-9]+-interfaces']
    paths: ['packages/interfaces/**', '.github/workflows/publish-interfaces.yml']
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
          token: ${{ secrets.PAT_SERVICE_ACCOUNT }}

      - name: Install jq
        uses: dcarbone/install-jq-action@v2.0.1

      - name: Extract tag name without v prefix
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV && echo "::set-output name=version::${GITHUB_REF#refs/tags/v}"
        env:
          GITHUB_REF: ${{ github.ref }}

      - name: 'Get Semantic Version from tag'
        if: github.event_name == 'push'
        run: |
          # Get the tag from the event
          tag=${GITHUB_REF#refs/tags/v}
          # remove the -interfaces suffix
          new_version=$(echo $tag | sed -n 's/-interfaces//p')
          echo $new_version
          # Replace the old version with the new version in package.json
          jq --arg version "$new_version" '.version = $version' packages/interfaces/package.json > /tmp/package.json && mv /tmp/package.json packages/interfaces/package.json

          # Print the new version
          echo "Updated package.json version to: $new_version"
          cat packages/interfaces/package.json

      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm install
        working-directory: packages/interfaces

      - name: Build
        run: npm run build
        working-directory: packages/interfaces

      - name: Publish to npm
        if: github.event_name == 'push'
        run: npm publish --access public
        working-directory: packages/interfaces
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

